const style = {
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  language: {
    flex: 2,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: 10,
  },
  btnKorean: {
    width: 50,
    height: 25,
    borderRadius: 5,
    backgroundColor: 'white',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  btnEnglish: {
    width: 50,
    height: 25,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'white',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  korean: {
    fontSize: 10,
    fontWeight: 'bold',
  },
  english: {
    fontSize: 10,
    fontWeight: 'bold',
    color: 'white',
  },
  title: {
    flex: 6,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  title_logo: {
    width: '80%',
    height: '40%',
    resizeMode: 'contain',
  },
  title__name: {
    display: 'flex',
    marginTop: 10,
    alignItems: 'center',
  },
  title__name_korean: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  title__name_english: {
    fontSize: 9,
    color: 'white',
  },
  topBoxs: {
    flex: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  btnNotification: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 190,
    height: 220,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  btnMenu: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 190,
    height: 220,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  bottomBoxs: {
    flex: 9,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  btnNotice: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 120,
    height: 220,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  btnRules: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 120,
    height: 220,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  btnInquiries: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 120,
    height: 220,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  icon: {
    width: 50,
    height: 50,
  },
  empty: {
    flex: 5,
    display: 'flex',
    flexDirection: 'row',
  },
};
export default style;
